services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 5173:5173
        command: sh -c "while true; do sleep 3600; done"